apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: graphql-gateway
      context: .
      docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/holden3148/graphql-gateway:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
  - name: dev
    build:
      artifacts:
        - docker: {}
      tagPolicy:
        envTemplate:
          template: '{{.DOCKER_REGISTRY}}/holden3148/graphql-gateway:{{.DIGEST_HEX}}'
      local: {}
    deploy:
      helm:
        releases:
          - name: graphql-gateway
            chartPath: charts/graphql-gateway
            setValueTemplates:
              image.repository: '{{.DOCKER_REGISTRY}}/holden3148/graphql-gateway'
              image.tag: '{{.DIGEST_HEX}}'
