apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/holdeneasley/graphql-gateway:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/holdeneasley/graphql-gateway:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: graphql-gateway
        chartPath: charts/graphql-gateway
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/holdeneasley/graphql-gateway'
          image.tag: '{{.DIGEST_HEX}}'
